### ISSUE TITLE
上传文件 错误7071

### ISSUE THREAD

**Issue by rachpt** [rachpt/lanzou-gui#1]
出现这种情况可能是云端检测到文件与后缀格式不匹配所致，出现在rar 分卷压缩得到的文件。就算使用浏览器也是同样的错误。使用 fake 文件也是无效。唯一保险的办法是二次压缩，也就是将分卷小包再次压缩得到正常的压缩文件。

考虑新的策略是：

先将大文件(大于100M) split 成小文件(不使用压缩软件，直接切二进制文件)，然后分别压缩(zip或则其他)。下载时，解压再合并即可。

--------
多次尝试很谜，估计我的账号被重点照顾了...

**Comment by zaxtyson** [comment]
蓝奏云官方对 *.part[0-9]+.rar 后缀做了限制，防止用户上传分卷压缩文件，API v2.2已修复这个问题😋

**Comment by rachpt** [comment]
> 蓝奏云官方对 *.part[0-9]+.rar 后缀做了限制，防止用户上传分卷压缩文件，API v2.2已修复这个问题yum

好的，有空试试。
