### ISSUE TITLE
客户端频繁停止工作

### ISSUE THREAD

**Issue by 15230745073** [rachpt/lanzou-gui#12]
客户端频繁出现停止工作，望作者予以解决😭
![频繁停止工作](https://user-images.githubusercontent.com/37293905/75128343-92a21880-56fe-11ea-95a7-a22a3ab1839a.png)

**Comment by rachpt** [comment]
运行环境得说一下，windows，版本？ 可执行程序还是直接运行源代码？

图片能使用 图床吗 (https://sm.ms  等)？我这里 github 连接性不好，看不到图片。  :grimacing:

**Comment by 15230745073** [comment]
win10环境 直接下载的您释放的可执行程序 图片已上传图床https://sm.ms/image/b5DVPNweJcCndYX

**Comment by rachpt** [comment]
这是带 控制台的打包程序： https://www.lanzous.com/i9n5ruj

如果可以的话看看 有没有错误输出。或者安装python环境运行源代码，看看是什么错误提示。

ps. 对了现在蓝奏云限制了登录(有滑动验证码)，可以用旧的 config.pkl  或者 手动输入 cookie

**Comment by 15230745073** [comment]
好的 我试下 有什么问题我再向您反馈

**Comment by 15230745073** [comment]
停止运行的情况应该是因为我移动硬盘的问题 我上传电脑本地的文件未出现这种情况
停止运行是cmd输出的错误是回溯错误 提示进程无法访问
不过我向您反馈下 我上传超过100m的文件上传成功后只显示一个文件夹 什么也看不到 是不是被蓝奏云封掉了🙏

**Comment by rachpt** [comment]
> 
> 
> 停止运行的情况应该是因为我移动硬盘的问题 我上传电脑本地的文件未出现这种情况
> 停止运行是cmd输出的错误是回溯错误 提示进程无法访问
> 不过我向您反馈下 我上传超过100m的文件上传成功后只显示一个文件夹 什么也看不到 是不是被蓝奏云封掉了🙏

可以用网页上传一下带有 你设置的 分卷后缀名的文件，看是不是能够正常上传

**Comment by 15230745073** [comment]
上传不上去😭换后缀名也不行 蓝奏云是不是更新策略了

**Comment by 15230745073** [comment]
经过多次尝试发现停止运行不单是因为移动硬盘的原因 我移动硬盘造成的是频繁停止 而换作本地文件也会出现 只是频率下降了
error的错误贴一下 https://sm.ms/image/NCm2zyka9dDJOIt
原因就是程序在调用rmtree删除的时候因为程序占用原因而造成停止运行
我去查看了一下您使用的api.py文件原作者还真写了易出现bug 贴图https://sm.ms/image/bOG4d6rtPusFCf9
我去zaxtyson/LanZouCloud-API看了下api有更新
试问下更新下api是不是能把这个bug修复掉

**Comment by 15230745073** [comment]
将软件中的后缀名设置成数字比如00 就可以正常上传大于100m的了
