### ISSUE TITLE
无法登录

### ISSUE THREAD

**Issue by MUTI-Thread** [rachpt/lanzou-gui#16]
![image](https://user-images.githubusercontent.com/31734364/75650329-81be4d80-5c90-11ea-8b10-89d0f1fb56fb.png)

**Comment by MUTI-Thread** [comment]
应该不是我输入错误，确认了好几次

**Comment by rachpt** [comment]
使用cookie登录先，因为蓝奏登录加入了滑动验证

**Comment by rachpt** [comment]
v0.0.9 已经修复。
