### ISSUE TITLE
上传文件损坏

### ISSUE THREAD

**Issue by 1015127214** [rachpt/lanzou-gui#18]
上传没问题，但是压缩包上传上去之后，再去下载，压缩包不知道变成什么文件了。

**Comment by rachpt** [comment]
可以看看这个 issue，能大致了解新版本 api (v2.4.0) 对于不支持文件以及大文件的处理方式。

当然该项目主要目的是方便正常使用。

**Comment by 1015127214** [comment]
> 可以看看这个 issue，能大致了解新版本 api (v2.4.0) 对于不支持文件以及大文件的处理方式。
> 
> 当然该项目主要目的是方便 **正常** 使用。

恩恩，主要是说解决了大文件的处理方式，我想试试，100多一点的，好几G的，我都试过了，压缩包上传上去之后就自动解压了，里面的文件也不知道是什么了，就是想问下这个大文件上传怎么使用，谢谢

**Comment by rachpt** [comment]
> > 可以看看这个 issue，能大致了解新版本 api (v2.4.0) 对于不支持文件以及大文件的处理方式。
> > 当然该项目主要目的是方便 **正常** 使用。
> 
> 恩恩，主要是说解决了大文件的处理方式，我想试试，100多一点的，好几G的，我都试过了，压缩包上传上去之后就自动解压了，里面的文件也不知道是什么了，就是想问下这个大文件上传怎么使用，谢谢

忘记贴连接了  :grin: 
https://github.com/zaxtyson/LanZouCloud-CMD/issues/16

**Comment by 1015127214** [comment]
> > > 可以看看这个 issue，能大致了解新版本 api (v2.4.0) 对于不支持文件以及大文件的处理方式。
> > > 当然该项目主要目的是方便 **正常** 使用。
> > 
> > 
> > 恩恩，主要是说解决了大文件的处理方式，我想试试，100多一点的，好几G的，我都试过了，压缩包上传上去之后就自动解压了，里面的文件也不知道是什么了，就是想问下这个大文件上传怎么使用，谢谢
> 
> 忘记贴连接了 😁
> [zaxtyson/LanZouCloud-CMD#16](https://github.com/zaxtyson/LanZouCloud-CMD/issues/16)

好的，谢谢，想问一下，这个里面上传的文件之后会失效嘛？是不是只能用这个工具下载，我用别的工具下载下来就不行了？

**Comment by rachpt** [comment]
> > > > 可以看看这个 issue，能大致了解新版本 api (v2.4.0) 对于不支持文件以及大文件的处理方式。
> > > > 当然该项目主要目的是方便 **正常** 使用。
> > > 
> > > 
> > > 恩恩，主要是说解决了大文件的处理方式，我想试试，100多一点的，好几G的，我都试过了，压缩包上传上去之后就自动解压了，里面的文件也不知道是什么了，就是想问下这个大文件上传怎么使用，谢谢
> > 
> > 
> > 忘记贴连接了 😁
> > [zaxtyson/LanZouCloud-CMD#16](https://github.com/zaxtyson/LanZouCloud-CMD/issues/16)
> 
> 好的，谢谢，想问一下，这个里面上传的文件之后会失效嘛？是不是只能用这个工具下载，我用别的工具下载下来就不行了？

---------

> 不知道您说的是 文件失效 还是 上传文件(非蓝奏支持的文件)这种方法？
- 文件的话，据说是一段时间没有下载后就会被清理，然而我貌似还没有遇到过；
- 至于目前这个上传 大文件与不支持类型文件的方法，有可能后期被蓝奏封杀。

>  是不是只能用这个工具？
- 如果是正常类型的文件(大小、类型都符合蓝奏要求)，下载用啥就没有关系了；
- 如果是 _特殊_ 文件，则只能使用 [zaxtyson/LanZouCloud-API](https://github.com/zaxtyson/LanZouCloud-API) 相关的项目，比如该项目以及 [zaxtyson/LanZouCloud-CDM](https://github.com/zaxtyson/LanZouCloud-CMD) 。
