### ISSUE TITLE
可执行文件v0.0.9 文件夹上传直接停止工作

### ISSUE THREAD

**Issue by 15230745073** [rachpt/lanzou-gui#19]
可执行文件v0.0.9上传文件客户端直接停止工作，经实验不管要上传的文件有没有子文件夹

**Comment by rachpt** [comment]
需要提供更多信息，或者参考隔壁 issue，https://github.com/zaxtyson/LanZouCloud-CMD/issues/24

**Comment by 15230745073** [comment]
> 需要提供更多信息，或者参考隔壁问题，[zaxtyson / LanZouCloud-CMD＃24](https://github.com/zaxtyson/LanZouCloud-CMD/issues/24)

好的

**Comment by 15230745073** [comment]
上面描述不清楚，应该是上传文件夹出现停止工作。上传文件目前稳定，不管文件大小都能成功，但是上传文件夹会出现停止工作，不管文件夹有没有子文件夹

**Comment by rachpt** [comment]
好的，好像是bug。当时没有测试 文件夹

**Comment by rachpt** [comment]
打包了一个修复版(win64)：https://www.lanzous.com/ia1lh2b
就不 release了

**Comment by 15230745073** [comment]
> 打包了一个修复版(win64)：https://www.lanzous.com/ia1lh2b
> 就不 release了

收到，感谢维护
