### ISSUE TITLE
win10启动出现错误Fatal error detected版本lanzou-gui win64 v0.1.0-beta.2

### ISSUE THREAD

**Issue by 857076222** [rachpt/lanzou-gui#20]
Failed to execute script main

**Comment by rachpt** [comment]
好像是有些设备需要在打包是加上` --hidden-import  xxx`其中xxx是提示找不到的包，显示的导入。
可能是需要一个完全没有Python的环境才能出现。

对了 文件路径最好使用 英文路径，

这是**新**打包的 v0.1.0
https://www.lanzous.com/iabqm3c

如果可以的话，麻烦测试一下是否能正常运行。

```
python.exe "D:\pyinstaller\pyinstaller.py" -Fw --hidden-import=PyQt5.sip -i ".\lanzou-gui\application_icon.ico" --version-file ".\lanzou-gui\pyinstaller_version_info.txt" .\lanzou-gui\main.py
```
