### ISSUE TITLE
windows客户端文件夹显示问题

### ISSUE THREAD

**Issue by lucky-top** [rachpt/lanzou-gui#21]
问题描述：
1. win10系统，使用客户端v0.1.0版本，上传文件正常，新建文件夹A失败；
2. 登陆网页版lanzous，显示未成功新建文件夹A；
3. 网页版新建文件夹B成功，并整理部分文件（C、D、E）至新建文件夹B；
4. 再次打开客户端，文件C、D、E消失（实际上已移动到文件夹B），并无法找到新建文件夹B；
5. 使用F5刷新，无效；
6. 登出后再次登陆，仍无效。

**Comment by rachpt** [comment]
1. 是不是文件夹级数超过了4？

2. 文件夹不能包含一些特殊字符，具体可以网页尝试

3. 你是不是把 `新建文件夹B`的父文件夹删掉了，这样的话 你这个文件夹就看不到了，（直接可能删不掉，如果是客户端先删掉父目录，网页没有刷新，就创建 文件夹B，就会出现孤儿文件夹，在移动文件的时候可以看见，但是没有办法切换目录进去）

图：
[![8UBQ10.png](https://s1.ax1x.com/2020/03/17/8UBQ10.png)](https://imgchr.com/i/8UBQ10)
[![8UBuhn.png](https://s1.ax1x.com/2020/03/17/8UBuhn.png)](https://imgchr.com/i/8UBuhn)

**Comment by lucky-top** [comment]
非常感谢作者更新到0.2.0版本。
win10版本号18363.719
删除了之前的0.1.0版本，并使用最新cookies登陆新版本0.2.0。
为了说明问题，请看一下客户端和网页端的对比截图。
![Snipaste_2020-03-27_20-25-02](https://user-images.githubusercontent.com/35058288/77756004-59e0c080-7069-11ea-948f-4d1f05be3ccf.png)
上图是客户端的
![Snipaste_2020-03-27_20-26-10](https://user-images.githubusercontent.com/35058288/77756256-cb207380-7069-11ea-96a2-1e710667b477.png)
上图网页端的
可以看到我描述的问题，根文件夹有一个文件夹，在客户端并不显示，，，，

**Comment by rachpt** [comment]
尝试一下右键移动文件，看能不能看到没有显示的文件夹。

我不知道这是不是api的bug，如果可以，麻烦用一下cmd版本的看看能不能显示。

**Comment by lucky-top** [comment]
反馈
1. gui客户端，右键移动文件。显示了endnote文件夹，且pdf移动成功。如图
![Snipaste_2020-03-27_21-55-36](https://user-images.githubusercontent.com/35058288/77764107-0f664080-7077-11ea-9d50-b5423ec22850.png)
2. cmd版本。登陆后，显示如图，无endnote文件夹
![Snipaste_2020-03-27_22-01-53](https://user-images.githubusercontent.com/35058288/77764122-14c38b00-7077-11ea-8796-4c3df4492bf1.png)
难道是api的bug？

**Comment by rachpt** [comment]
那应该就是api方面的bug了，
我推测这个endnote为非正常创建的文件夹，回收站恢复或者其他什么的。

如果里面文件不多，可以重新建一个文件夹，将文件移动进去，以暂时解决这个问题。

**Comment by rachpt** [comment]
> 反馈
> 
> 1. gui客户端，右键移动文件。显示了endnote文件夹，且pdf移动成功。如图
>    ![Snipaste_2020-03-27_21-55-36](https://user-images.githubusercontent.com/35058288/77764107-0f664080-7077-11ea-9d50-b5423ec22850.png)
> 2. cmd版本。登陆后，显示如图，无endnote文件夹
>    ![Snipaste_2020-03-27_22-01-53](https://user-images.githubusercontent.com/35058288/77764122-14c38b00-7077-11ea-8796-4c3df4492bf1.png)
>    难道是api的bug？

如果可以，能把打开 `https://pc.woozooo.com/mydisk.php?item=files&action=index` 的网页源码看打包发一下吗。
目测是这行代码没匹配到 endnote 那一行。
https://github.com/rachpt/lanzou-gui/blob/79f3c764add034fb810b7095f384966f0bc908cc/lanzou/api/core.py#L352

**Comment by lucky-top** [comment]
继续反馈，请看截图，用谷歌浏览器登陆蓝奏网页版直接查看源码
![Snipaste_2020-03-29_10-37-34](https://user-images.githubusercontent.com/35058288/77838793-9b788500-71a9-11ea-8c7c-e460bf48868d.png)
圆圈附近的两块代码是这样的
`<a href="mydisk.php?item=files&action=index&folder_node=1&folder_id=1279505"><img src="images/folder_open.gif" border="0" align="absmiddle" />&nbsp;mathtype</a>&nbsp;<span onmouseover="folkey(1279505)"; onMouseOut="folkeycl(1279505)"; class="fkey" id="folk1279505" style="display:initial"> `
以及
`<a href="mydisk.php?item=files&action=index&folder_node=1&folder_id=1519538"><img src="images/folder_open.gif" border="0" align="absmiddle" />&nbsp;endnote</a>&nbsp;<span onmouseover="folkey(1519538)"; onMouseOut="folkeycl(1519538)"; class="fkey" id="folk1519538" style="display:initial">`

**Comment by rachpt** [comment]
应该是是 文件夹描述 里面有`回车符`导致的bug，可以复现

**Comment by lucky-top** [comment]
多谢作者。
确实是“文件夹描述”里面的“回车符”导致的bug。
刚才修改了文件夹描述，结果如图。
![Snipaste_2020-03-29_12-04-51](https://user-images.githubusercontent.com/35058288/77840048-6d00a700-71b5-11ea-83f9-faaac7cddc3f.png)
