### ISSUE TITLE
文件夹无法显示的问题

### ISSUE THREAD

**Issue by guhailong18** [rachpt/lanzou-gui#23]
几天前用的还是好好地，今天打开来发现文件夹看不到了，但是如果新建文件夹的话，可以在网页端看到新建成功，已试过登出并重新登录
![image](https://user-images.githubusercontent.com/56160866/77924327-235bad80-72d6-11ea-9d46-77d8817fa97d.png)

**Comment by guhailong18** [comment]
抱歉，刚刚更新的信息没有弹出来

**Comment by rachpt** [comment]
github 的 api 我是经常被拒绝连接，v0.2.1 加入了 gitee 作为备用更新 api，以后应该会弹出来的 :smile:

**Comment by guhailong18** [comment]
新版本也有bug，无法新建文件夹，会闪退

**Comment by rachpt** [comment]
> 新版本也有bug，无法新建文件夹，会闪退

一会儿更新 :grin:
