### ISSUE TITLE
上传大文件100M以上，下载后无法还原

### ISSUE THREAD

**Issue by Roseloverman** [rachpt/lanzou-gui#27]
你好，这个软件在windows上，上传100M以上的文件后，在下载下来是一堆各种格式的文件，无法自动生成原始文件

**Comment by rachpt** [comment]
自有下载下个这个 `100M 以上` 的文件对应的文件夹，才能还原这个 文件，不能进入文件夹使用批量下载。
不是的是不是直接下载的文件夹？

**Comment by MyTlyer** [comment]
大于100M文件上传成功，直接下载的文件夹，但是下载后的文件还是单个各种格式的文件，不能自动合并是什么情况？

**Comment by MrTlyer** [comment]
重新上传了一次，整个文件夹下载能成功自动合并能打开，但是WIN版本V0.2.3主程序显示未响应，稳定性有待改进@rachpt

**Comment by Roseloverman** [comment]
@MrTlyer ，你好我的是window文件夹版本，我将文件夹的分享链接和提取码复制提取后为什么还是里面的各个文件，不是整个文件夹下载，请问有什么注意的细节么？

**Comment by Roseloverman** [comment]
@rachpt 将大文件上传后，生成了一个文件夹，然后用这个文件夹的分享外链和提取码，提取文件后，就成了里边包含的单个文件，下载后就无法自动还原了。

**Comment by rachpt** [comment]
> @rachpt 将大文件上传后，生成了一个文件夹，然后用这个文件夹的分享外链和提取码，提取文件后，就成了里边包含的单个文件，下载后就无法自动还原了。

使用未登录提取下载的情况确实没有考虑到，我估计 cmd 版本也没有考虑到这种情况。
我看看能不能加进去

**Comment by rachpt** [comment]
v0.2.4 已经修复
