### ISSUE TITLE
支持下linux平台不？

### ISSUE THREAD

**Issue by jingle0927** [rachpt/lanzou-gui#28]

**Comment by rachpt** [comment]
???
本来初衷就是给Linux开发的，windows只是顺带支持🤣

**Comment by jingle0927** [comment]
> ???
> 本来初衷就是给Linux开发的，windows只是顺带支持

求大佬打包linux

**Comment by rachpt** [comment]
> > ???
> > 本来初衷就是给Linux开发的，windows只是顺带支持
> 
> 求大佬打包linux

打包？
Linux 不需要打包，直接从源代码运行。(可以自己写一个 .desktop 文件，双击运行)
这又不是编译型语言，不需要也没有二进制文件。

**Comment by SuperEndermanSM** [comment]
> > > ???
> > > 本来初衷就是给Linux开发的，windows只是顺带支持
> > 
> > 
> > 求大佬打包linux
> 
> 打包？
> Linux 不需要打包，直接从源代码运行。
> 这又不是编译型语言，不需要也没有二进制文件。
> 
> 先clone代码，装好 requestments.txt 里面的依赖后，直接运行 main.py就行了(可执行权限应该是已经加了的)。(可以自己写一个 .desktop 文件，双击运行)
> KDE 环境 效果更好，毕竟 是 qt 的嘛。
> 在Linux下界面效果比 windows 好太多
> https://gitee.com/rachpt/lanzou-gui/wikis/Linux-KDE-Interface-Preview

报错提示
pip3 install pyqtwebengine -i https://pypi.tuna.tsinghua.edu.cn/simple
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting pyqtwebengine
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/47/9f/60e630711fd1dd14ef3bd95c86c733c86b8c0853749c7a03691f681f13fd/PyQtWebEngine-5.14.0.tar.gz (47kB)
    100% |████████████████████████████████| 51kB 976kB/s 
  Installing build dependencies ... done
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/lib/python3.7/tokenize.py", line 447, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-6xcs2mqv/pyqtwebengine/setup.py'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-6xcs2mqv/pyqtwebengine/
