### ISSUE TITLE
0.0.5版本上传文件闪退

### ISSUE THREAD

**Issue by ShaneLee-9** [rachpt/lanzou-gui#3]

**Comment by rachpt** [comment]
可能是网络不稳定引起的，后续我更新一下lanzou-api试试。目前的 lanzou-api 是经过部分修改了的，不能直接升级

**Comment by ShaneLee-9** [comment]
> 可能是网络不稳定引起的，后续我更新一下lanzou-api试试。目前的 lanzou-api 是经过部分修改了的，不能直接升级

老哥很稳，之前一直用的你的lanzou-cmd
