### ISSUE TITLE
v0.2.6 功能都差不多了

### ISSUE THREAD

**Issue by rachpt** [rachpt/lanzou-gui#32]
具体见 https://github.com/rachpt/lanzou-gui/projects/1
开机启动好像意义不大，需要的自行创建 快捷方式至  windowns 开机启动文件夹。

还有一个自定义分享链接 个性域名的功能，不过感觉没必要。

前前后后加了 15 个功能，:laughing:。

以后不再新增功能，仅维护能用。

**Comment by snk100** [comment]
这里下载的版本，登陆会闪退。
https://github.com/rachpt/lanzou-gui/releases

**Comment by rachpt** [comment]
> 这里下载的版本，登陆会闪退。
> https://github.com/rachpt/lanzou-gui/releases

 v0.2.7 已修复

**Comment by snk100** [comment]
> @snk100
> v0.2.7 已修复

感谢修复。
