### ISSUE TITLE
关于 PD 事件

### ISSUE THREAD

**Issue by zaxtyson** [rachpt/lanzou-gui#35]
前两天 PanDownload 的事情让我感到咱们现在有一点危险，我国这方面的法律本就不够完善，直接给用户提供这种工具可能不太好。目前 CMD 版几乎接近 700 用户下载，GUI 版应该用户更多，如此一来可能要对蓝奏云的正常运营造成影响，也有用户提议关闭上传大文件的功能 https://github.com/zaxtyson/LanZouCloud-CMD/issues/44#issue-602406829
CMD 版我打算过段时间去掉大文件上传功能，保留基本功能。API 的使用不加限制，由其它开发者自行考虑和承担风险，减少大量普通用户的涌入。

**Comment by rachpt** [comment]
已经计划去除 https://github.com/rachpt/lanzou-gui/issues/33

**Comment by rachpt** [comment]
大文件上传功能 已经关闭
