### ISSUE TITLE
关于下载100M以上的文件

### ISSUE THREAD

**Issue by DIUHKJN** [rachpt/lanzou-gui#36]
你好，我是一名Rom制作者，现在急缺一个保存时间久、可以上传大文件、不限速的网盘，以前我用谷歌云盘搭下载站，但总是有人反映速度慢。现在觉得你这个下载100M以上的文件的功能挺不错，不过最近PD确实也有不少影响，我的建议是把这个东西单独整成一个小软件，就是输上链接自动下载加合成，然后最好不要直接发软件，最近这么严，安全也不好保证

**Comment by rachpt** [comment]
以后（v0.2.7+）会关闭支持上传大文件的设置入口（可以自己修改源代码打开），下载的策略不会变。

**Comment by bdrwss** [comment]
怎么修改源代码？
