### ISSUE TITLE
文件上传后，下载闪退

### ISSUE THREAD

**Issue by Roseloverman** [rachpt/lanzou-gui#37]
你好，0.2.5和0.2.6的windows版本，将大文件上传后，下载会出现闪退，可能是个bug，请尽快修复一下，谢谢！

**Comment by rachpt** [comment]
如还有问题，请打开调试日志，附上 log 能快速定位问题所在。

**Comment by Roseloverman** [comment]
@rachpt 你好，我的意思是上传文件后，用提取码的方式下载会出现闪退。我看了de-bug log是个空文件

**Comment by 993986695** [comment]
客户端登入不上了，一直都是提示账号密码错误
