### ISSUE TITLE
对 API 重构

### ISSUE THREAD

**Issue by rachpt** [rachpt/lanzou-gui#4]
https://github.com/zaxtyson/LanZouCloud-API 的逻辑并不完全适用于GUI的设计思路，现需要重构才能满足GUI多线程的需求，CMD版本因为是单线程阻塞运行的，所以该API几乎完全没有考虑多线程多任务的情况。

现思路如下：
- 将登录情况的 fid 弱化，仅作为获取 分享链接 提取码等信息的 请求数据；所有文件文件夹因该以 分享链接+提取码 作为唯一标识(而不是 fid)；一个链接对应一个文件(夹)，所有文件(夹)都有分享链接

- 登录与不登陆的区别：登录可以得到一堆的分享链接与提取码，不登录只能自己一个个输入(批量输入也可以考虑)

- 单独唯一的的下载方法：对于下载文件，登录与不登陆没有本质区别，都是 分享链接+提取码。

**Comment by zaxtyson** [comment]
😄其实很久以前就有人提issue，要加上多线程和进度条，然后我发现下载速度已经满带宽了（莫非是我网速妙）😢就只加入回调函数处理进度条，哈哈😗

**Comment by zaxtyson** [comment]
获取分享链接需要发送一个 POST，如果以分享链接+提取码作为唯一标识，每一次加载主界面需要的请求就比较多了。设计 API 的时候是考虑尽可能减少每个 method 发送的请求数量(怕被官方ban)。多线程的话，那就得重构一下 `down_file_by_url()` ，其它下载方法最后都是基于它。upload 开多线程会出问题的哦👌。
