### ISSUE TITLE
No module named 'ui_lanzou'

### ISSUE THREAD

**Issue by DoveBoy** [rachpt/lanzou-gui#40]
Python 3.8.2
运行0.2.7版本，无法运行，没有ui_lanzou模块，pip无法找到并下载这个模块

**Comment by rachpt** [comment]
之间 使用 qt 生成的 ui 代码， 是 Ui_lanzou.py，最近我在里面改了些东西，顺便将文件名小写了，因为 windows 文件系统不区分文件名大小写，但是 `python` 区分，所以 使用 `git clone` 的时候 文件名字可能没改过来，自己改一下，或则重新 clone 或则 下载 zip。

**Comment by bdrwss** [comment]
这个怎么改呢

**Comment by DoveBoy** [comment]
> 之间 使用 qt 生成的 ui 代码， 是 Ui_lanzou.py，最近我在里面改了些东西，顺便将文件名小写了，因为 windows 文件系统文件名不区分大小写，但是 `python` 区分，所以 使用 `git pull` 的时候 文件名字可能没改过来，自己改一下，或则重新 clone 或则 下载 zip。

现在用最新版的代码运行，又提示No module named 'PyQt5.QtWebEngineWidgets'，pip同样没法找到，怎么解决，小白一个，能说的具体点吗？谢谢

**Comment by rachpt** [comment]
@DoveBoy 
如果不是 32 位系统
```
pip install PyQtWebEngine
```
或者在代码文件夹 `pip install -r requirements.txt  --user`
