### ISSUE TITLE
大文件上传不了，这个怎么修改？需要修改什么？

### ISSUE THREAD

**Issue by bdrwss** [rachpt/lanzou-gui#42]
大文件上传不了，这个怎么修改？需要修改什么？

**Comment by rachpt** [comment]
https://github.com/rachpt/lanzou-gui/commit/f8c22036181eb187545f9c2d80f79938ec76c21f

```
self.big_file_box.setDisabled(True)
```
不建议上传大文件！

**Comment by bdrwss** [comment]
> [f8c2203](https://github.com/rachpt/lanzou-gui/commit/f8c22036181eb187545f9c2d80f79938ec76c21f)
> 
> ```
> self.big_file_box.setDisabled(True)
> ```
> 
> 不建议上传大文件！

因为不想用某盘，想用咱们这个客端户代替

**Comment by bdrwss** [comment]
self.big_file_box.setDisabled(True)

这是什么东西？？？怎么用？
