### ISSUE TITLE
登陆错误

### ISSUE THREAD

**Issue by zhaoruihang** [rachpt/lanzou-gui#45]
为什么我使用windows版的登陆不上我的账号

**Comment by rachpt** [comment]
因为最近手机版的登录也加入了阿里的滑动验证，这个验证很难破解。

要么使用从最新的源码运行(使用PyQtWebEngine打开网页获取 cookie)，打包版本只能自行输入 cookie 登录。

**Comment by karsacui** [comment]
+1，正在使用旧版，不敢退出账号
