### ISSUE TITLE
0.2.7.7登录 提示 密码不对

### ISSUE THREAD

**Issue by akunssssd** [rachpt/lanzou-gui#48]
看样子是 接口挂了，14号作者更新过，说明Py那个软件 还是可用的。
请问是否拥有c++源码？
我还是比较习惯使用windows 执行程序。

**Comment by rachpt** [comment]
因为蓝奏加入了 阿里h5滑动验证.
如果使用 源码运行会 使用 PyQtWebEngine 打开登录web获取 cookie，如下：
![Snipaste_2020-06-15_13-27-37](https://user-images.githubusercontent.com/25758867/84621302-c94daa00-af0c-11ea-9073-50ece3b4ad53.png)


由于 PyQtWebEngine  的加入，打包Windows可执行程序会有 260 MB 的体积，
后面如果有时间会将 登录部分(PyQtWebEngine) 单独做一个辅助程序

c++，没有。

**Comment by akunssssd** [comment]
好的，谢谢您了，因为网络上，我实在没找到可以直接使用的windows版本。

**Comment by akunssssd** [comment]
> 因为蓝奏加入了阿里h5滑动验证。
> 如果使用二进制运行会使用PyQtWebEngine：登录网络获取cookie，如下：
> ![Snipaste_2020-06-15_13-27-37](https://user-images.githubusercontent.com/25758867/84621302-c94daa00-af0c-11ea-9073-50ece3b4ad53.png)
> 
> 由于PyQtWebEngine的加入，打包Windows安装程序会有260 MB的体积，
> 后面如果有时间调用登录部分（PyQtWebEngine）单独做一个辅助程序
> 
> c ++，没有。

好的，谢谢您了，因为网络上，我实在没找到可以直接使用的Windows版本。

您可以通过让他挂载程序网页窗口，用户自行登录完直接跳到软件里。
