### ISSUE TITLE
0.3.0登陆问题

### ISSUE THREAD

**Issue by AzlmZ-del** [rachpt/lanzou-gui#49]
win10 2004
账号密码+cookie登陆没反应，在登陆过程中切屏就闪退
login_assister.exe用了完全没反应

**Comment by rachpt** [comment]
设置中打开 debug，附上  debug-lanzou-gui.log 中的信息

**Comment by AzlmZ-del** [comment]
我没动过任何文件，但debug-lanzou-gui.log打开是空白。。。。。。

**Comment by MikerAlex** [comment]
我这边点击打开cookie栏，发现cookie被清理了，我重新输入了一遍，解决了



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "AzlmZ-del"<notifications@github.com&gt;; 
发送时间: 2020年6月17日(星期三) 晚上6:45
收件人: "rachpt/lanzou-gui"<lanzou-gui@noreply.github.com&gt;; 
抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 
主题: [rachpt/lanzou-gui] 0.3.0登陆问题 (#49)





 
win10 2004
 账号密码+cookie登陆没反应，在登陆过程中切屏就闪退
 login_assister.exe用了完全没反应

**Comment by rachpt** [comment]
提问需要描述清楚，不然没人能够帮助解决问题。
- _切屏就闪退_，切屏？
- _用了完全没反应_，怎么用的真的不用说一下？
- 打开是空白，有打开 设置 开启调试日志码？

。

**Comment by AzlmZ-del** [comment]
好吧，是我没说清楚
第一个问题，账号密码输入后，点登陆会卡很久，我想切屏换其他应用，但是切完软件，lanzou-gui就强行终止进程了
第二个问题，其实算第一个的附加问题，就是我按开发者的方法登陆，一直卡在登陆页面，然后软件要么怎么点都没反应，要么就卡成无响应
第三个问题，确定开启了调试日志，但debug-lanzou-gui.log就是空白（我放在非系统盘运行的，以前的版本没问题，不知0.3.0行不行）

**Comment by rachpt** [comment]
1. _**卡很久**_：login_assister.exe 打包了 PyQtWebEngine，相当于打包了一个**完整的现代浏览器**，打开时，会先在 temp 目录解压(超过 200MB)在运行，自然慢；(所有点击登录后只能耐心等待)
2. _**推荐 手动输入 cookie 登录**_，辅助程序做的也是 获取 cookie 而已，仅此；
3. _**辅助程序是阻塞主线程的**_，当然不能乱操作(点击)，否则gui当然会失去响应。一次登录就有效，所以就像这样，毕竟可以自己输入 cookie。

**Cookie 登录的说明：**
1. 输入用户名，
2. 点击  `显示 cookie 登录框`，
3. 填入 `ylogin=12341234;phpdisk_info=xxxxxxxxxxxxxxxxxxxxxxxxx`，修改其中的 `数字` 与 `xxxxx`部分,
4. 点击登录。

**只要有输入 cookie 值，就会只使用 cookie 值**，用户名目前必须输入，用于区分不同用户。  
cookie 保存在本地，有效期很长……

我的表述应该够清楚了吧 :)

**Comment by AzlmZ-del** [comment]
我确实是按照你说的输入的啊，也等了很久，但是点了添加用户后程序就再也没有反应了/笑哭

**Comment by rachpt** [comment]
> 
> 
> 我确实是按照你说的输入的啊，也等了很久，但是点了添加用户后程序就再也没有反应了/笑哭

是 使用 辅助程序登录是吧？cookie 登录于此是两个完全不同的问题。

使用 辅助程序：
windows defender 会弹出 

C:\users\你的用户名\appdata\local\temp\_mei117842\pyqt5\qt\bin\qtwebengineprocess.exe
在 使用网络吧？

_mei117842 是是随机的

我使用 固态硬盘需要等待接10秒才能打开 辅助程序 的登录界面，机械硬盘可能更慢，

可以在  C:\users\你的用户名\appdata\local\temp\ 查看是否有 一个  类似 _mei117842  的文件夹被解压

**Comment by AzlmZ-del** [comment]
仔细确认了几遍，确实没有_mei******类似的文件，登陆方法两个都试过了，也把程序移动到了C盘，都没用，看来这版本确实用不了，我还是用0.2.7吧（😂）

**Comment by rachpt** [comment]
已经添加新的登录方式。
