### ISSUE TITLE
#

### ISSUE THREAD

**Issue by zd423** [rachpt/lanzou-gui#5]

**Comment by zaxtyson** [comment]
API v2.3.2 已修复该 Bug，原因是蓝奏云上传接口启用了 https，使用 http 上传会得到 302 重定向的响应。另外修复了官方对文件名携带多重后缀的限制(比如`图片.jpg.dll`、`图片.jpg哈哈.dll` 这样的文件不允许上传)。[CMD版](https://github.com/zaxtyson/LanZouCloud-CMD)已经修复。

**Comment by mrdong916** [comment]
什么时候修复啊

**Comment by rachpt** [comment]
> 什么时候修复啊

按照 @zaxtyson 的说法，只需要在下面一行将 http 改成 https 即可解决上传bug。
https://github.com/rachpt/lanzou-gui/blob/56bd72724c29e84bfeaff4c1a51347293ff32325/lanzou/api.py#L633
。
至于打包可以参考wiki：
python.exe "D:\pyinstaller\pyinstaller.py" -F -w -i ".\lanzou-gui\application_icon.ico" --version-file ".\lanzou-gui\pyinstaller_version_info.txt" .\lanzou-gui\main.py

最后，因为纵所周知的原因，被困在农村，没有条件测试和打包，希望有条件的同学pr😘
