### ISSUE TITLE
无法获取带有提取码的链接

### ISSUE THREAD

**Issue by FYdz99** [rachpt/lanzou-gui#50]
感谢分享，辛苦辛苦
问题：无法获取带有提取码的链接，按照指示输入“链接+空格/汉字+提取码”，依然获取失败
劳烦解答，多谢

**Comment by rachpt** [comment]
能麻烦提供一下 失效链接 吗？

**Comment by FYdz99** [comment]
> 能麻烦提供一下 失效链接 吗？

https://nan-gua.lanzous.com/b015ckkba 密码:6duc

**Comment by rachpt** [comment]
fixed.

**Comment by FYdz99** [comment]
太感谢了，爱您
