### ISSUE TITLE
非法链接使提取界面无法回弹

### ISSUE THREAD

**Issue by BoyceLig** [rachpt/lanzou-gui#52]
一开始别人给我的是这样的链接 https://wwa.lanzous.com/ikkHRdxaqda 我用浏览器是可以打开的，提示非法链接
![image](https://user-images.githubusercontent.com/49801599/85347738-07aa2100-b52c-11ea-972a-6e4f71e2c071.png)
后来我换成了这个，还是提示非法链接
https://www.lanzous.com/ikkHRdxaqda

**Comment by rachpt** [comment]
截图上显示的是  https://www.lanzous.com/ikk ？

**Comment by BoyceLig** [comment]
但是我复制时候是完整的地址

**Comment by rachpt** [comment]
![Screenshot_20200623_090612](https://user-images.githubusercontent.com/25758867/85349415-fc0d2900-b530-11ea-90ea-315e66356c0b.png)

**Comment by BoyceLig** [comment]
我链接那块是灰色的 点不了  是因为我登录了的原因么

**Comment by BoyceLig** [comment]
我刚打开的地址是可以添加的，我一复制地址的时候，她就自动识别剪贴板，变灰。左下角提示非法链接

**Comment by rachpt** [comment]
这应该是另外一个 bug
:(

**Comment by BoyceLig** [comment]
这个链接在剪贴板他提示为非法链接，也算个bug
