### ISSUE TITLE
使用了最新的lanzou-gui_win64_v0.3.1版本，也使用了辅助助手，提示错误，无登陆滑动成功。

### ISSUE THREAD

**Issue by snk100** [rachpt/lanzou-gui#53]
具体看图。https://s1.ax1x.com/2020/06/24/NaLQ2Q.png

**Comment by rachpt** [comment]
这场已知问题，可以把这个界面拉大一些，点击一下其他页面再 点击登录，重新滑动。
滑动时最好慢一点

**Comment by snk100** [comment]
> 这时已知问题，可以把这个界面拉大一些，点击一下其他页面再 点击登录，重新滑动。
> 滑动时最好慢一点

根据提示操作成功了，感谢作者回复我。
