### ISSUE TITLE
暂停下载的文件无法重新下载

### ISSUE THREAD

**Issue by FYdz99** [rachpt/lanzou-gui#54]
软件已经趋于完美，但是当下载的文件数量 大于 所设置的“同时下载文件数”时，超出规定数量的文件会暂停下载，点击“开始”或“开始所有任务”都没有反应，只能重启软件。
有劳解决，辛苦辛苦

**Comment by rachpt** [comment]
感谢，已修复 ☺

**Comment by FYdz99** [comment]
> 感谢，已修复

辛苦辛苦，优化后简直赞到飞起，献上膝盖_(:з」∠)_
