### ISSUE TITLE
批量下载无响应

### ISSUE THREAD

**Issue by VengaXu** [rachpt/lanzou-gui#55]
虽然能看流量监控判断是否下载完 但下载过程及之后程序无响应只能强制关闭重开

**Comment by VengaXu** [comment]
系统win10

**Comment by rachpt** [comment]
1. 是最新的版本(commit)？之前有几个 commit 可能有这个问题
2. `无响应` 是指 任务管理 tab 不能及时(或者不正确)显示下载进度，还是软件 崩溃失去响应？

最近重构了任务管理部分的逻辑，可能会有一些隐藏的 bug 😣

**Comment by VengaXu** [comment]
> 1. 是最新的版本(commit)？之前有几个 commit 可能有这个问题(任务管理 tab 更新不及时)
> 2. `无响应` 是指 任务管理 tab 不能及时(或者不正确)显示下载进度，还是软件 崩溃失去响应？
> 
> 最近重构了任务管理部分的逻辑，可能会有一些隐藏的 bug 😣

3.1的 不显示下载进度且失去响应 但是着实在下载 速度四五十兆好评 就是每次都得等下完了强制关闭进程再开 单个百兆文件好像就没问题
