### ISSUE TITLE
[Enhancement] Backgroud Image Reduce the Menu Bar's Readability.

### ISSUE THREAD

**Issue by whriedplanck** [rachpt/lanzou-gui#57]
如下图：
![Running Screenshot](https://i.loli.net/2020/07/17/2B379b5OUYpxFi1.png)

这个《你的名字。》的背景很好看，但是设计上降低了页面（尤其是菜单栏）一些元素的可读性。希望可以默认改善一下，谢谢 ～

**Comment by rachpt** [comment]
已调整。
感谢，之前一直使用的全局菜单，没有发现 😅
效果图：
![Screenshot_20200717_155839.png](https://i.loli.net/2020/07/17/Us1KNC4dfJzIVWi.png)

**Comment by whriedplanck** [comment]
> 已调整。

太棒啦，感谢你的工作！
