### ISSUE TITLE
[Notification (and suggestion)] lanzou-gui is available in AUR

### ISSUE THREAD

**Issue by whriedplanck** [rachpt/lanzou-gui#58]
This program has been packaged and uploaded to AUR. : ) ( But not by me )
这个程序已打包并上传至 AUR : ) (不过不是我上传的)

See here: https://aur.archlinux.org/packages/lanzou-gui/
可以看上行链接

P.S. I notice you statement abot Linux version in #28 ...
我注意到你在 #28 提到的关于 Linux 版本的问题...
> > > ???
> > > 本来初衷就是给Linux开发的，windows只是顺带支持
> > 
> > 求大佬打包linux

> 打包？
> Linux 不需要打包，直接从源代码运行。
> 这又不是编译型语言，不需要也没有二进制文件。

_Originally posted by @rachpt in https://github.com/rachpt/lanzou-gui/issues/28#issuecomment-611340969_

This isn't pretty right. In general, you should create a `setup.py` for this project at least.
这其实不太对。总的来说，你应该至少创建一个 `setup.py` 文件。

For example, you can see this project: [FeelUOwn](https://github.com/feeluown/FeelUOwn) (its a plug-in [feeluown-netease](https://github.com/feeluown/feeluown-netease), both are available in AUR: [FeelUOwn AUR](https://aur.archlinux.org/packages/feeluown/) and [feeluown-netease AUR](https://aur.archlinux.org/packages/feeluown-netease/)) . Their PKGBUILDs is good to learn.
举例来说，你可以看看这个项目: FeelUOwn (和它的插件 feeluown-netease)，两者都能在 AUR 找到（链接均在上段）。它们的 PKGBUILD 构建脚本也能很好说明这类 Python 程序是怎么被打成软件包的。

Best wishes！
祝越做越好！

**Comment by rachpt** [comment]
OK, I'll do it later.
Thanks!

**Comment by whriedplanck** [comment]
> OK, I'll do it later.
> Thanks!

No problem. Thanks for accepting my suggestion ~

**Comment by whriedplanck** [comment]
Thanks for your work ～！
