### ISSUE TITLE
上传文件时会自动修改空格为下划线

### ISSUE THREAD

**Issue by mrdong916** [rachpt/lanzou-gui#6]
上传文件时会自动修改空格为下划线，这样不太好吧，不可以进行编码后上传吗？

**Comment by rachpt** [comment]
> 上传文件时会自动修改空格为下划线，这样不太好吧，不可以进行编码后上传吗？

这个得问写 api 的 @zaxtyson，那条注释表示不解，Linux文件路径可以包含空格。

**Comment by mrdong916** [comment]
> > 上传文件时会自动修改空格为下划线，这样不太好吧，不可以进行编码后上传吗？
> 
> 这个得问写 api 的 @zaxtyson，那条注释表示不解，Linux文件路径可以包含空格。

我用Windows上用CMD那个版本是可以的 但是用Mac的话GUI版本不行
