### ISSUE TITLE
遇到的问题：1、部分链接提取不了文件夹内容；2、全选后下载遇到错误文件会中断

### ISSUE THREAD

**Issue by Code-Cats** [rachpt/lanzou-gui#60]
1、部分链接（无密码）提取不了文件夹内容
换了网或者挂了VPN也还是提取不了，应该和网络环境无关
2、全选后下载遇到部分无法下载的文件会中断整个文件包的下载
全选后点击下载会自动创建文件夹，下载中会有些文件会出错（err='content-length'） 出错后若点击重新尝试会从头下载并在相同的位置再次出错 （该出错文件在网页上可以直接正常下载），后面的文件是其实可以正常下载的，但是因为出错文件会中断整个文件包下载，只能自己去单独跳过出错文件去选中下载后面的部分，还早软件是按照顺序下载的，记下已经下了多少，在文件选择界面直接选择剩下的文件重新下载。
小小的提议：
1、提示无法提取文件包内容的原因
2、文件包全选下载遇到出错文件跳过继续下载后面的部分，最后提示那些下载错误。

**Comment by rachpt** [comment]
可能是你所说的这个文件使用了特殊名字，或者是html界面文件大小中有 `,`符号 https://github.com/zaxtyson/LanZouCloud-API/commit/ec5098b0c0638647fcb4c7757d7f0dfabd169b39 。
没有更多信息，也只能猜测原因了。

**Comment by naruhodo-cc** [comment]
同遇到提取不了的问题，我的有提取码，等了老半天文件内显示不出来。
网页打开文件夹均显示正常，就是软件里没办法提取……

![image](https://user-images.githubusercontent.com/5347002/91888513-02e9b200-ecbf-11ea-848e-100f0a9f1a3e.png)
