### ISSUE TITLE
无法登录lanzou-gui，一直提示请添加辅助程序，添加辅助程序后不管是等待多久都没有登陆上，多次点击添加账户会程序无响应，只有cookie没有辅助程序会提示你添加，添加了又登不上，v0.3.3和v0.3.2均是如此，换成v0.2.7秒登

### ISSUE THREAD

**Issue by MikerAlex** [rachpt/lanzou-gui#66]

**Comment by rachpt** [comment]
用cookie登录试试。打开浏览器获取，或者复制0.2.7（登录对话框显示cookie）到 0.3.3登录对话框 cookie输入栏

**Comment by MikerAlex** [comment]
输入cookie后登录会提示请添加辅助程序，添加辅助程序就登陆不上，卡多久都不行，要么无响应要么没反应。只用cookie总是提示添加辅助程序，不添加登录不了那种
像是这样

添加了登录辅助程序后就会无响应卡死，
现在换回了0.2.7版本使用。







------------------&nbsp;原始邮件&nbsp;------------------
发件人: "rachpt"<notifications@github.com&gt;; 
发送时间: 2020年8月27日(星期四) 上午7:20
收件人: "rachpt/lanzou-gui"<lanzou-gui@noreply.github.com&gt;; 
抄送: "1208266550"<1208266550@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [rachpt/lanzou-gui] 无法登录lanzou-gui，一直提示请添加辅助程序，添加辅助程序后不管是等待多久都没有登陆上，多次点击添加账户会程序无响应，只有cookie没有辅助程序会提示你添加，添加了又登不上，v0.3.3和v0.3.2均是如此，换成v0.2.7秒登 (#66)





 
用cookie登录试试。打开浏览器获取，或者复制0.2.7（登录对话框显示cookie）到 0.3.3登录对话框 cookie输入栏

**Comment by MikerAlex** [comment]
现在问题不是辅助程序卡死，而是只用cookie无法登录，用了辅助程序就卡死，是一个死循环




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "rachpt"<notifications@github.com&gt;; 
发送时间: 2020年8月27日(星期四) 上午7:20
收件人: "rachpt/lanzou-gui"<lanzou-gui@noreply.github.com&gt;; 
抄送: "1208266550"<1208266550@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [rachpt/lanzou-gui] 无法登录lanzou-gui，一直提示请添加辅助程序，添加辅助程序后不管是等待多久都没有登陆上，多次点击添加账户会程序无响应，只有cookie没有辅助程序会提示你添加，添加了又登不上，v0.3.3和v0.3.2均是如此，换成v0.2.7秒登 (#66)





 
用cookie登录试试。打开浏览器获取，或者复制0.2.7（登录对话框显示cookie）到 0.3.3登录对话框 cookie输入栏

**Comment by xllxll** [comment]
同样的问题，登录不了了
