### ISSUE TITLE
对有-的密码链接无法解析

### ISSUE THREAD

**Issue by chandy89830** [rachpt/lanzou-gui#68]
如题，对密码含“-”这样符号的链接无法正确提取，只能识别-前面的部分，另外一些无敏感字的TXT或压缩包也会网络中断或出错，无法下载

**Comment by drb0** [comment]
同问。有的自定义域名（带了“-”）的分享链接一直无法解析，而且替换成wwi.lanzoux.com或wwi.lanzous.com也显示“非法链接”，但这三个链接其实在浏览器中都可以正常打开。

**Comment by rachpt** [comment]
链接？
<img width="995" alt="图片" src="https://user-images.githubusercontent.com/25758867/104085874-b2e2b380-528d-11eb-8897-0146d13eece4.png">

https://i.loli.net/2021/01/09/Z6KuP9Uix7HBcyW.png

**Comment by drb0** [comment]
> 链接？
> <img alt="图片" width="995" src="https://user-images.githubusercontent.com/25758867/104085874-b2e2b380-528d-11eb-8897-0146d13eece4.png">
> 
> https://i.loli.net/2021/01/09/Z6KuP9Uix7HBcyW.png

那天确实反复试了好几次也没能解析一直提示“非法链接”但在浏览器能打开。不过我今天发现了release里的新版本，也可能因为我之前用的是旧的版本（上次没找到在哪里下载新的）？不过上次我遇到的那个链接现在已经被取消分享啦。那我下次遇到这种的再试！谢谢！

**Comment by Avon998** [comment]
同问，更新为新版本V0.3.7仍然有这个问题，对后半部分含“-”这样符号的链接无法正确提取，例如：https://XXX-XXX.lanzoux.com/s/JikssyShsb5Ah-d

**Comment by rachpt** [comment]
这个链接 是后面部分有问题
https://xx.lanzoux.com/s/JikssyShsb5Ah-d
后面的 -d  不能识别。lanzou 之前所有的 uri  都是不包含 - 的
这种会员自定义链接 需要提供一个 uri 可用符合列表，api方面添加匹配规则。

https://github.com/rachpt/lanzou-gui/issues/84
