### ISSUE TITLE
能否增加大文件切分合并功能

### ISSUE THREAD

**Issue by Wanghp119** [rachpt/lanzou-gui#71]
能否使用 [hjsplit](https://hjsplit.en.softonic.com/) 将大文件切分为小文件再上传
下载的时候再自动合并。

**Comment by MikerAlex** [comment]
这个别问了，以前有这个功能，现在已经删除了那部分源码，毕竟蓝奏云和蓝奏gui都挺好用的






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "rachpt/lanzou-gui"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月16日(星期五) 中午11:07
收件人:&nbsp;"rachpt/lanzou-gui"<lanzou-gui@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[rachpt/lanzou-gui] 能否增加大文件切分合并功能 (#71)





 
能否使用 hjsplit 将大文件切分为小文件再上传
 下载的时候再自动合并。

**Comment by rachpt** [comment]
https://github.com/rachpt/lanzou-gui/blob/cf8a2fa9b7bff2ed7468e61476a75b64cc4f6f9b/lanzou/gui/dialogs/setting.py#L66

https://github.com/rachpt/lanzou-gui/issues/42

可以自己在源代码打开，还能不能用，我也不知道。🤭
