### ISSUE TITLE
自己摸索的使用Cookie登陆情况 【用辅助程序登录卡死登陆不上的可以试试】

### ISSUE THREAD

**Issue by kokokeke001** [rachpt/lanzou-gui#72]
我今天才发现这个工具，真好用，谢谢大佬。

基于release v0.3.3
> 
>     输入用户名，
>     点击 显示 cookie 登录框，
>     填入 ylogin=12341234;phpdisk_info=xxxxxxxxxxxxxxxxxxxxxxxxx 修改其中的 数字 与 xxxxx部分,
>     点击 添加用户。
大佬这里可能描述有问题
我自己用辅助程序登录后，查看cookie登陆框，里面p在前，ylogin在后，所以cookie我自己怎么填写都说没填[0.3.3版]，
用辅助程序登录卡死登陆不上的可以试试，顺序换一下。phpdisk_info=xxxxxxx;ylogin=12341234这样的顺序填写cookie
firefox浏览器【版本81】获取cookie
lanzou正常登陆后看见自己的网盘内容了，点键盘【F12】
下面查看器那行的【存储】标签
左列【cookie】双击展开
选网址【pc.woozooo.com】也许你的不一样
右侧表单里面有4项分别是
我们要的
【phpdisk_info=xxxxxxx】
【ylogin=12341234】
和不要的
【PHPSESSID】和【folder_id_c】
按格式

**phpdisk_info=xxxxxxx;ylogin=12341234**

从表单里面吧数据放到等号后面，分别替换xxx和12341234，保持英文分号【;】分隔，填到工具cookie输入框里面，
这时：
用户名随意，有就行【仅用于自己区分不同网盘账号】
密码不用填【用cookie不用密码】
cookie可能得再粘贴一次【填写的用户名变动会清空cookie】
添加用户/登陆

**Comment by MikerAlex** [comment]
问题的确解决了，原来简单的把phpdisk_info和ylogin换个方向就行了😂😂😂😂😂😂




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "kokokeke001"<notifications@github.com&gt;; 
发送时间: 2020年10月19日(星期一) 中午1:39
收件人: "rachpt/lanzou-gui"<lanzou-gui@noreply.github.com&gt;; 
抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 
主题: [rachpt/lanzou-gui] 自己摸索Cookie 登录的说明【用辅助程序登录卡死登陆不上的可以试试】 (#72)





 
我今天才发现这个工具，真好用，谢谢大佬。
 
基于release v0.3.3
  输入用户名， 点击 显示 cookie 登录框， 填入 ylogin=12341234;phpdisk_info=xxxxxxxxxxxxxxxxxxxxxxxxx 修改其中的 数字 与 xxxxx部分, 点击 添加用户。   
大佬这里可能描述有问题
 我自己用辅助程序登录后，查看cookie登陆框，里面p在前，ylogin在后，所以cookie我自己怎么填写都说没填[0.3.3版]，
 用辅助程序登录卡死登陆不上的可以试试，顺序换一下。phpdisk_info=xxxxxxx;ylogin=12341234这样的顺序填写cookie
 firefox浏览器【版本81】获取cookie
 lanzou正常登陆后看见自己的网盘内容了，点键盘【F12】
 下面查看器那行的【存储】标签
 左列【cookie】双击展开
 选网址【pc.woozooo.com】也许你的不一样
 右侧表单里面有4项分别是
 我们要的
 【phpdisk_info=xxxxxxx】
 【ylogin=12341234】
 和不要的
 【PHPSESSID】和【folder_id_c】
 按格式
 
phpdisk_info=xxxxxxx;ylogin=12341234
 
从表单里面吧数据放到等号后面，分别替换xxx和12341234，保持英文分号【;】分隔，填到工具cookie输入框里面，
 这时：
 用户名随意，有就行【仅用于自己区分不同网盘账号】
 密码不用填【用cookie不用密码】
 cookie可能得再粘贴一次【填写的用户名变动会清空cookie】
 添加用户/登陆

**Comment by tangm421** [comment]
真的是，需要把ylogin和phpdisk_info换个位置才行，不然老是提示没有输入cookie。
另外，我是chorme，开始使用的是地址栏的锁图标里的cookie，但是总提示登录失败，后来使用F12，查看Application里面的Cookies发现phpdisk_info的值和地址栏锁图标里面cookie的值不一样。使用F12方式里面的cookie就可以了成功登录了！
![Snipaste_2020-12-24_11-18-27](https://user-images.githubusercontent.com/26132858/103057184-d2b18080-45d9-11eb-83cd-d880ca77e813.png)

**Comment by misaka-h** [comment]
确实解决了，无需辅助程序，也不要账号密码，非常感谢！
那么主程序里的说明确实应该改一下了。

**Comment by evilglass** [comment]
多谢楼上的，感动哭了，原来f12和直接查看的不一样（后者会少很多），另外还是无法登录，关闭程序重打开一遍。

**Comment by 1716001473** [comment]
为啥显示为什么我显示用户名或密码错误？
