### ISSUE TITLE
三个排序都有bug

### ISSUE THREAD

**Issue by khinacid** [rachpt/lanzou-gui#73]
问题：排序bug
版本：window GUI 0.3.3
详细描述：点击时间排序，结果看起来好像是正序，但是“21天前”怎么在“2分钟前”？

![20201026200857](https://user-images.githubusercontent.com/41636243/97171955-41848000-17c9-11eb-8bc8-0e246a71d703.png)

仔细想想，是软件在排序上对时间数值和单位处理有问题。

排序的另一问题是，按名称排序居然是大小写敏感，例如abc.apk和Abc.apk居然不是紧挨着。我看到大多数资源管理器对大小都是不敏感的，例如windows资源管理器

此外，体积排序也有问题：

![20201026202558](https://user-images.githubusercontent.com/41636243/97172264-c1aae580-17c9-11eb-92ef-f368b1674bfa.png)

一共就三个排序，都有问题。😰

对排序功能要求严格是很有必要的：**通过对比系统文件夹列表和蓝奏云客户端列表的文件来检查上传文件是否有遗漏和错误**。

期待开发者检查该问题并修补。

**Comment by rachpt** [comment]
首先这个排序功能是 pyqt5 的tableview控件提供的功能，应该使用的显示字符排序。
时间的话，可以在设置中使用格式化的时间，实现排序（精度到天）。
目前需求不是那么迫切，后面可以考虑优化一下。

**Comment by mrdong916** [comment]
大哥 优化一下吧 找东西排序不准确 找好久都找不到 还没有搜索功能

**Comment by rachpt** [comment]
已修复。
