### ISSUE TITLE
网址能否去掉前缀

### ISSUE THREAD

**Issue by liveskai** [rachpt/lanzou-gui#77]
http://www.lanzou.com/abcdefg 改为 http://lanzou.com/abcdefg 
去掉www，带前缀的链接经常性打不开

**Comment by rachpt** [comment]
**客户端的定位** 是自己文件的管理、批量操作，以及文件夹链接的批量提取下载。

日常单文件下载建议直接使用浏览器下载。

蓝奏的二级域名打不开，与运营商网络相关，改个公关dns或者自己改一下 lanzous  lanzoui   lanzoux
