### ISSUE TITLE
能不能加上对其他浏览器cookie获取的支持？

### ISSUE THREAD

**Issue by NobodyHere-rrr** [rachpt/lanzou-gui#79]
希望加上对Edge，Safari之类的浏览器的cookie获取支持,手动获取老是报错.

**Comment by rachpt** [comment]
依赖于 browser-cookie3 模块的支持

https://github.com/borisbabic/browser_cookie3/pull/70

**Comment by rachpt** [comment]
v0.3.7，Edge 已支持。
