### ISSUE TITLE
能支持软件自动更新嘛？

### ISSUE THREAD

**Issue by wuzhumeng** [rachpt/lanzou-gui#80]
如题，每次更新都要重新解压，重新登录，能加个软件自动更新功能吗？

**Comment by rachpt** [comment]
登录：可以复制 旧软件目录下的 config.pkl  到新目录，即可保持之前状态。

嫌解压麻烦，可以安装python环境，clone 源代码运行，更新时 pull 一下代码即可。

如果没有可以忍受更新日志提到的bug，不需要新的feature，可以在设置中关闭自动更新检测。
