### ISSUE TITLE
新版本重复文件下载出错

### ISSUE THREAD

**Issue by chandy89830** [rachpt/lanzou-gui#83]
旧版本中若链接中有重复文件会跳过不会下载，新版本有重复文件被选择下载会下载成一个文件自动合并，导致文件打开出错

**Comment by rachpt** [comment]
这个是因为文件断点下载功能 会将同名文件当做同一个文件处理。
所以不要同时下载文件夹下的同名文件。

旧版 可能是指没有任务管理的版本，使用文件名判断，现在的版本都是使用 文件 url 进行唯一判断。
