### ISSUE TITLE
对提取码是四字中文的，程序无法提取密码

### ISSUE THREAD

**Issue by Avon998** [rachpt/lanzou-gui#85]
如题，作者大大，提取码是两个中文字的可以解析提取码，但是提取码是四个中文字的，链接就无法提取，会显示“请在链接后面跟上提取码，空格分割”

**Comment by drb0** [comment]
同出现这个问题了
![image](https://user-images.githubusercontent.com/61258654/106379623-318fc400-63e8-11eb-9f04-c0a2eeff1d41.png)

**Comment by rachpt** [comment]
@drb0 先用中文或者英文的冒号（：）分割一下。
后面会加入一个提取码输入框，处理这种乱七八糟的提取码。
