### ISSUE TITLE
上传文件失败,之前是可以的

### ISSUE THREAD

**Issue by Leon406** [rachpt/lanzou-gui#91]
是不是上传api改了

**Comment by drb0** [comment]
同问，今天突然文件和文件夹都无法上传了。上传失败的文件夹都创立了空文件夹。要么直接显示“出错了”，要么显示“已完成”却也无法在网盘里查看到所上传内容。
![image](https://user-images.githubusercontent.com/61258654/109505869-fe6c4d80-7ad7-11eb-8e43-4f60d7859b19.png)

**Comment by rachpt** [comment]
https://github.com/zaxtyson/LanZouCloud-API/pull/52
明天我合并一下代码

**Comment by mrdong916** [comment]
> [zaxtyson/LanZouCloud-API#52](https://github.com/zaxtyson/LanZouCloud-API/pull/52)
> 明天我合并一下代码

催促一下大佬 还有tar.gz也加上

**Comment by zaxtyson** [comment]
的确是官方在搞事情, 马上更新~
