### ISSUE TITLE
客户端对文件后缀支持存在大小写的问题

### ISSUE THREAD

**Issue by sixyin** [rachpt/lanzou-gui#92]
使用网页端大小写均可以正常上传，但是使用客户端的话必须要把文件后缀改为全部小写才支持，否则随机更改文件后缀后上传
使用客户测试结果如下：
```
test.appimage 正常上传 
test.AppImage 随机更改后缀
test.appImage 随机更改后缀
```
应该是只需要把文件后缀在上传匹配的时候全部转为统一的大小写就可以了

**Comment by rachpt** [comment]
收到，后面我调整一下忽略后缀名大小写
@zaxtyson

https://github.com/zaxtyson/LanZouCloud-API/blob/507db3d11eda8a13c51c7a831b84c8e98e36f8a6/lanzou/api/utils.py#L76

**Comment by zaxtyson** [comment]
收到, 马上改
